Documentation update (#4)
* Updated documentation and CI

* Removed dep on 'either' crate, documented connection::stream module

* Moved login logic from ExaWebSocket to PlainWebSocket

* Fixed attribute schema update

* Added SocketSpawner trait

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -50,77 +50,121 @@ jobs:
       - uses: actions-rs/cargo@v1
         with:
           command: clippy
-          args: --features ${{ matrix.etl }}${{ matrix.features }}${{ matrix.compression }}
+          args: --tests --features ${{ matrix.etl }}${{ matrix.features }}${{ matrix.compression }}
         env:
           RUSTFLAGS: -D warnings
 
-  # test:
-  #   name: Testing
-  #   needs: clippy
-  #   runs-on: ubuntu-20.04
-  #   steps:
-  #     - name: Set up Python 3.10
-  #       uses: actions/setup-python@v3
-  #       with:
-  #         python-version: "3.10"
+  sqlx_tests:
+    name: SQLx tests
+    needs: clippy
+    runs-on: ubuntu-20.04
+    services:
+      exasol:
+        image: exasol/docker-db:7.0.22
+        ports:
+          - 8563:8563
+        options: --privileged
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: Install dependencies
-  #       run: |
-  #         python -m pip install --upgrade pip
-  #         pip install pipenv
+      - name: Setup Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
 
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         repository: exasol/docker-db
-  #         ref: "7.0.22"
+      - uses: Swatinem/rust-cache@v2
 
-  #     - name: Set up Exasol Cluster
-  #       run: |
-  #         docker pull exasol/docker-db:7.0.22
-  #         pipenv install -r exadt_requirements.txt
-  #         pipenv run ./exadt create-cluster --root ~/sqlx/ --create-root sqlx
-  #         pipenv run ./exadt init-cluster --image exasol/docker-db:7.0.22 --license ./license/license.xml --num-nodes 3 --auto-storage sqlx
-  #         pipenv run ./exadt start-cluster sqlx
+      - name: Create connection strings
+        run: |
+          echo "NO_TLS_URL=exa://sys:exasol@127.0.0.1:8563?ssl-mode=disabled" >> $GITHUB_ENV
+          echo "TLS_URL=exa://sys:exasol@127.0.0.1:8563?ssl-mode=required" >> $GITHUB_ENV
 
-  #     - uses: actions/checkout@v3
+      - name: Tests not requiring a connection
+        run: cargo test
 
-  #     - name: Setup Rust toolchain
-  #       uses: actions-rs/toolchain@v1
-  #       with:
-  #         profile: minimal
-  #         toolchain: stable
-  #         override: true
+      - name: Connection tests
+        run: DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono -- --nocapture
 
-  #     - name: Create connection strings
-  #       run: |
-  #         CONTAINER_ID=`docker ps --format "table {{.ID}}\t" | head -2 | tail -1`
-  #         EXA_IP=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID`
-  #         echo $EXA_IP
-  #         echo "NO_TLS_URL=exa://sys:exasol@$EXA_IP:8563?ssl-mode=disabled" >> $GITHUB_ENV
-  #         echo "TLS_URL=exa://sys:exasol@$EXA_IP:8563" >> $GITHUB_ENV
+      - name: TLS connection tests
+        run: DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono -- --nocapture
 
-  #     - name: Run tests
-  #       run: |
-  #         # Tests not requiring a connection
-  #         cargo test
+      - name: Connection tests with compression
+        run: DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,compression -- --ignored
 
-  #         # Tests without ETL or compression
-  #         DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono
+      - name: TLS connection tests with compression
+        run: DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,compression -- --ignored
 
-  #         # Tests without ETL
-  #         DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono,compression
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono,compression
+  etl_tests:
+    name: ETL tests
+    needs: clippy
+    runs-on: ubuntu-20.04
+    services:
+      exasol:
+        image: exasol/docker-db:7.0.22
+        ports:
+          - 8563:8563
+        options: --privileged
+    steps:
+      - uses: actions/checkout@v3
 
-  #         # ETL tests without compression
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features etl && exit 1
-  #         DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features etl -- --ignored --nopcature --test-threads 4
-  #         DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features etl_native_tls -- --ignored --nopcature --test-threads 4
-  #         DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features etl_rustls -- --ignored --nopcature --test-threads 4
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features etl_native_tls -- --ignored --nopcature --test-threads 4
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features etl_rustls -- --ignored --nopcature --test-threads 4
+      - name: Setup Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
 
-  #         # ETL tests with compression
-  #         DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features etl,compression -- --ignored --nopcature  --test-threads 4
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features etl_native_tls,compression -- --ignored --nopcature  --test-threads 4
-  #         DATABASE_URL=${{ env.TLS_URL }} cargo test --features etl_rustls,compression -- --ignored --nopcature --test-threads 4
+      - uses: Swatinem/rust-cache@v2
+
+      - name: Create connection strings
+        run: echo "NO_TLS_URL=exa://sys:exasol@127.0.0.1:8563?ssl-mode=disabled" >> $GITHUB_ENV
+
+      - name: Tests compilation failure if both ETL TLS features are enabled
+        run: cargo test --features etl_native_tls,etl_rustls || true
+
+      - name: ETL non-TLS tests when TLS feature is provided (resorts to non-TLS)
+        run: |
+          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,compression,etl_native_tls -- --ignored --nocapture --test-threads 4
+          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,compression,etl_rustls -- --ignored --nocapture --test-threads 4
+
+      - name: ETL tests
+        timeout-minutes: 15
+        run: DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,compression,etl -- --ignored --nocapture  --test-threads 4
+
+  tls_etl_tests:
+    name: TLS ETL tests
+    needs: clippy
+    runs-on: ubuntu-20.04
+    services:
+      exasol:
+        image: exasol/docker-db:7.0.22
+        ports:
+          - 8563:8563
+        options: --privileged
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
+
+      - uses: Swatinem/rust-cache@v2
+
+      - name: Create connection strings
+        run: echo "TLS_URL=exa://sys:exasol@127.0.0.1:8563?ssl-mode=required" >> $GITHUB_ENV
+
+      - name: ETL without TLS feature but TLS connection (should fail)
+        run: DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,etl -- --ignored --nocapture --test-threads 4 || true
+
+      - name: Native-TLS ETL tests
+        timeout-minutes: 15
+        run: DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,compression,etl_native_tls -- --ignored --nocapture  --test-threads 4
+
+      - name: Rustls ETL tests
+        timeout-minutes: 15
+        run: DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,compression,etl_rustls -- --ignored --nocapture --test-threads 4
